import {MonsterType} from "@/types";
import {Usable} from "@/constants/items/usalbe-item/usable-info";
import {Material} from "@/constants/items/material/material-info";
import {ColdRegionFruits} from "@/constants/items/usalbe-item/bush-info";

export const IcyPlateauMonster = {
    IceSlime: {
        icon: '🔵',
        name: '冰霜史萊姆',
        description: '寒冷冰氣的冰屬性史萊姆，被攻擊的話有機率造成寒冷狀態。',
        level: 16,
        hp: 60,
        hpLimit: 60,
        ad: 16,
        adDefend: 15,
        apDefend: 15,
        hit: 10,
        dodge: 10,
        critRate: 10,
        critIncrease: 200,
        dropGold: 35,
        onAttack: 'frozenOnAttack',
        drop: [
            {item: Material.IceSlimeItem, chance: 0.33},
            {item: Material.LowerNormal, chance: 0.1}
        ],
    } as MonsterType,
    SnowBird: {
        icon: '🦢',
        name: '雪域白鷹',
        description: '與雪色相同潔白的羽色來隱藏自己的行蹤,從高衝甫落下來刺殺敵人。',
        level: 16,
        hp: 45,
        hpLimit: 45,
        ad: 20,
        adDefend: 10,
        apDefend: 10,
        hit: 10,
        dodge: 40,
        critRate: 25,
        critIncrease: 200,
        dropGold: 30,
        drop: [
            {item: Material.SnowBirdItem, chance: 0.33},
            {item: ColdRegionFruits.HotFruit, chance: 0.1},
            {item: Material.LowerNormal, chance: 0.1}
        ],
    } as MonsterType,

    SmallSnowGolem: {
        icon: '☃️',
        name: '小雪怪',
        description: '魔力吸引而生成的雪像魔物,有一定威脅性，被攻擊的話有機率造成寒冷狀態',
        level: 17,
        ad: 18,
        hp: 100,
        hpLimit: 100,
        adDefend: 15,
        apDefend: 10,
        hit: 12,
        dodge: 20,
        critRate: 25,
        critIncrease: 150,
        dropGold: 45,
        drop: [
            {item: Material.MagicSnowStone, chance: 0.1},
            {item: Material.LowerNormal, chance: 0.1}
        ],
        onAttack: 'frozenOnAttack',
    } as MonsterType,
    FrozenSkull: {
        icon: '💀',
        name: '冰凍骷髏',
        description: '被凍死在高原上的冒險者遺骸，靈魂因寒冷而痛苦不堪，被攻擊的話有機率造成寒冷狀態。',
        level: 19,
        hp: 85,
        hpLimit: 85,
        ad: 20,
        adDefend: 18,
        apDefend: 13,
        hit: 5,
        dodge: 5,
        critRate: 10,
        critIncrease: 200,
        dropGold: 50,
        drop: [
            {item: Material.MagicSnowStone, chance: 0.1},
            {item: Material.LowerNormal, chance: 0.1}
        ],
        onAttack: 'frozenOnAttack',
    } as MonsterType,
    IceSlime2: {
        icon: '🔵',
        name: '大冰霜史萊姆',
        description: '寒冷冰氣的冰屬性史萊姆，被攻擊的話有機會會被凍結。',
        level: 19,
        hp: 100,
        hpLimit: 100,
        ad: 20,
        adDefend: 17,
        apDefend: 17,
        hit: 10,
        dodge: 10,
        critRate: 10,
        critIncrease: 200,
        dropGold: 50,
        drop: [
            {item: Material.IceSlimeItem, chance: 0.5},
            {item: Material.LowerNormal, chance: 0.15}
        ],
        onAttack: 'frozenOnAttack',
    } as MonsterType,
    SnowBird2: {
        icon: '🦢',
        name: '極地白鷹',
        description: '與雪色相同潔白的羽色來隱藏自己的行蹤,從高衝甫落下來刺殺敵人。',
        level: 19,
        hp: 80,
        hpLimit: 80,
        ad: 25,
        adDefend: 10,
        apDefend: 10,
        hit: 15,
        dodge: 40,
        critRate: 25,
        critIncrease: 200,
        dropGold: 50,
        drop: [
            {item: Material.SnowBirdItem, chance: 0.5},
            {item: ColdRegionFruits.HotFruit, chance: 0.1},
            {item: Material.LowerNormal, chance: 0.15}
        ],
    } as MonsterType,

    SmallSnowGolem2: {
        icon: '☃️',
        name: '雪怪',
        description: '魔力吸引而生成的雪像魔物,有一定威脅性',
        level: 20,
        ad: 23,
        hp: 150,
        hpLimit: 150,
        adDefend: 20,
        apDefend: 15,
        hit: 12,
        dodge: 20,
        critRate: 25,
        critIncrease: 150,
        dropGold: 60,
        drop: [
            {item: Material.MagicSnowStone, chance: 0.2},
            {item: Material.LowerNormal, chance: 0.15}
        ],
        onAttack: 'frozenOnAttack',
    } as MonsterType,

    IceCrystalGargoyle: {
        icon: '𖤍',
        name: '冰晶石像鬼',
        description: '守護著冰雪遺跡的守衛，表皮覆蓋著堅硬的冰層。',
        level: 20,
        hp: 150,
        hpLimit: 150,
        ad: 35,
        adDefend: 45,
        apDefend: 45,
        hit: 10,
        dodge: 2,
        critRate: 5,
        critIncrease: 200,
        dropGold: 80,
        drop: [
            {item: Material.MagicSnowStone, chance: 0.3},
            {item: Material.LowerNormal, chance: 0.2}
        ],
    } as MonsterType,


    FrostTroll: {
        icon: '👹',
        name: '霜凍食人魔',
        description: '身材巨大的怪物，每一擊都能引起小型地震。',
        level: 22,
        hp: 240,
        hpLimit: 240,
        ad: 60,
        adDefend: 30,
        apDefend: 10,
        hit: 12,
        dodge: 0,
        critRate: 10,
        critIncrease: 200,
        dropGold: 120,
        drop: [{item: Material.LowerNormal, chance: 0.1}],
    } as MonsterType,
}