import {MonsterType} from "@/types";

export const ScorchedSandsMonster = {
    SandRabbit: {
        icon: '🐇',
        name: '沙漠兔',
        description: '在炙熱的沙漠中跳躍,狩獵方式是一腳踢死獵物',
        level: 6,
        hp: 60,
        hpLimit: 60,
        ad: 15,
        adDefend: 5,
        apDefend: 5,
        hit: 10,
        dodge: 25,
        critRate: 25,
        critIncrease: 150,
        dropGold: 25,
    } as MonsterType,

    CactusSpirit: {
        icon: '🌵',
        name: '仙人掌精',
        description: '會走路的植物，防禦較高且渾身佈滿尖刺，會對攻擊者噴射尖刺',
        level: 6,
        hp: 50,
        hpLimit: 50,
        ad: 8,
        adDefend: 15,
        apDefend: 15,
        hit: 8,
        dodge: 0,
        critRate: 5,
        critIncrease: 150,
        chaseIncrease: -10,
        dropGold: 20,
        onAttacked:'cactusSpiritOnAttacked'
    } as MonsterType,

    QuicksandWorm: {
        icon: '🪱',
        name: '流沙蟲',
        description: '在大地深處鑽洞的生物，動作難以捕捉',
        level: 7,
        hp: 100,
        hpLimit: 100,
        ad: 25,
        adDefend: 0,
        apDefend: 8,
        hit: 12,
        dodge: 20,
        critRate: 0,
        critIncrease: 100,
        dropGold: 20,
    } as MonsterType,

    DuneBeast: {
        icon: '🦖',
        name: '沙丘巨獸',
        description: '沙丘的領主，其吼聲能震落天上的飛鳥，但行動相對笨重，能跑就快跑吧',
        class: 'elite big',
        level: 15,
        hp: 1000,
        hpLimit: 1000,
        ad: 50,
        adDefend: 30,
        apDefend: 30,
        hit: 25,
        dodge: 4,
        critRate: 20,
        critIncrease: 200,
        chaseIncrease: -100,
        dropGold: 500,
    } as MonsterType,
}