// ⚔️ WEAPON (武器) - 主力輸出
import {EquipmentType} from "@/types";
import {EquipmentPosition} from "@/enums/enums";

export const Dagger = {
    Dagger0: {
        name: '生鏽匕首',
        description: '鐵鏽斑駁的舊匕首，鋒刃已鈍。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        critRate: 10,
        ad: 3,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
    Dagger1: {
        name: '普通匕首',
        description: '普通的短刀，簡單卻輕巧便攜。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        critRate: 13,
        ad: 6,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
    Dagger2: {
        name: '精良匕首',
        description: '經過細緻打磨的優質匕首。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        critRate: 16,
        ad: 12,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
    Dagger3: {
        name: '鋼鐵匕首',
        description: '精選優良鋼鐵鍛造而成，結構堅固的利刃。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        critRate: 19,
        ad: 24,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
    Dagger4: {
        name: '合金匕首',
        description: '融合多種稀有金屬鍛造，刀身呈現淡雅的暗金色澤。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        critRate: 22,
        ad: 48,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
    Dagger5: {
        name: '精鋼匕首',
        description: '以最高工藝鍛造的極致精鋼短刃，有相當的刺穿破壞力。',
        icon: '🔪',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        critRate: 25,
        ad: 96,
        adIncrease: -40,
        actionValue: 50,
    } as EquipmentType,
};

export const Sword = {
    Sword0: {
        name: '生鏽長劍',
        description: '劍身佈滿了暗紅色的鐵鏽，邊緣參差不齊。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        ad: 4,
    } as EquipmentType,
    Sword1: {
        name: '普通長劍',
        description: '來自城鎮鐵匠鋪的標準制式鐵劍。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        ad: 8,
    } as EquipmentType,
    Sword2: {
        name: '精良長劍',
        description: '工藝講究的雙刃長劍，劍身平衡經過精心調校。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        ad: 16,
    } as EquipmentType,
    Sword3: {
        name: '鋼鐵長劍',
        description: '以經過反覆淬火的冷鍛鋼鐵打造。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        ad: 32,
    } as EquipmentType,
    Sword4: {
        name: '合金長劍',
        description: '使用特殊合金鍛造，具備更精良的工藝與更多傷害。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        ad: 64,
    } as EquipmentType,
    Sword5: {
        name: '精鋼長劍',
        description: '加厚了護手並進行完美拉絲處理的精鋼佩劍。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        ad: 128,
        hit: 20,
    } as EquipmentType,
};

export const Axe = {
    Axe0: {
        name: '生鏽戰斧',
        description: '斑駁的生鏽單刃斧，雖然早已不復當年的光澤，但藉由重力墜下的破甲力依然強悍。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        hit: -20,
        ad: 5,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
    Axe1: {
        name: '普通戰斧',
        description: '粗獷大氣的雙手大鐵斧，巨大的斧面能在揮舞時對敵人施加排山倒海的沉重壓迫感。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        hit: -20,
        ad: 10,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
    Axe2: {
        name: '精良戰斧',
        description: '木柄纏繞防滑皮革的精良戰斧，刃角經過細心修正，使每一發劈砍都能精確釋放力量。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        hit: -20,
        ad: 20,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
    Axe3: {
        name: '鋼鐵戰斧',
        description: '採用精鍊碳鋼整體澆鑄而成的沉重戰斧，一擊便可粉碎敵人的盾牌與骨骼。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        hit: -20,
        ad: 40,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
    Axe4: {
        name: '合金戰斧',
        description: '使用高剛性輕量化合金製成的雙刃戰斧，巨大的形體下擁有出乎意料的揮動速度，威力橫掃千軍。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        hit: -20,
        ad: 80,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
    Axe5: {
        name: '精鋼戰斧',
        description: '工藝達到巔峰的精鋼巨斧，純黑的斧背與銀亮的斧刃形成強烈對比，是戰場上無人敢當的狂暴兇器。',
        icon: '🪓',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        hit: -20,
        ad: 160,
        isTwoHanded: true,
        skill: 'PowerCharge',
    } as EquipmentType,
};

export const MagicStick = {
    MagicStick0: {
        name: '生鏽法杖',
        description: '表皮剝落且金屬環生鏽的古老法杖，雖然年久失修，但內部仍迴盪著一絲倔強的魔力漣漪。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        ap: 5,
    } as EquipmentType,
    MagicStick1: {
        name: '普通法杖',
        description: '經過悉心打磨的法力木杖，沒有華麗的寶石點綴，但能穩定引導法師體內的精神能量。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 1,
        ap: 10,
    } as EquipmentType,
    MagicStick2: {
        name: '精良法杖',
        description: '刻有微光銘文的紫檀木杖，能有效降低法術施放時的遲滯感，是法術入門者的標準配置。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 2,
        ap: 20,
    } as EquipmentType,
    MagicStick3: {
        name: '鋼鐵法杖',
        description: '杖身包覆著鋼鐵防護的法杖，杖尖鑲嵌的晶石可大幅增幅佩戴者對四周元素的感應。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 3,
        ap: 40,
    } as EquipmentType,
    MagicStick4: {
        name: '合金法杖',
        description: '採用輕質合金與魔導木複合製成的法杖，杖頭懸浮的螢石無時無刻不在凝聚流動的魔能。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 4,
        ap: 80,
    } as EquipmentType,
    MagicStick5: {
        name: '精鋼法杖',
        description: '杖身刻滿精緻魔法迴路的精鋼秘法杖，將魔力的傳導損耗降至最低，釋放出最純粹的毀滅之力。',
        icon: '🪄',
        position: EquipmentPosition.WEAPON,
        quality: 5,
        ap: 160,
    } as EquipmentType,
};

export const SpecialWeapon = {
    WoodSword: {
        name: '木劍',
        description: '用木頭削成的劍，起始武器。',
        icon: '🗡️',
        position: EquipmentPosition.WEAPON,
        quality: 0,
        ad: 1,
    } as EquipmentType,
    SpikeSpear: {
        name: '尖刺木槍',
        icon: '🪾',
        description: '從枯死的魔樹枝幹削製而成的尖刺長槍,但使用時會奪去部分生命。',
        position: EquipmentPosition.WEAPON,
        ad: 10,
        hpLimit: -50,
        critRate: 10,
        hit: 5,
        quality: 11
    } as EquipmentType,
}

export const Weapon = {...Dagger, ...Sword, ...MagicStick, ...Axe}